config/routes.rb
Rails.application.routes.draw do



  resources :contents

  delete 'orders/delete_items/:id', to: 'orders#delete_items', as: 'delete_items'
  resources :orders
  get 'update_orders' => 'orders#update', :as => 'update'
  resources :outlet_produces

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions"}

  root 'welcome#index'
  get '*path', to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/content.rb
class Content < ApplicationRecord
  mount_uploader :image, PictureUploader
    # after_save :cloudinary_upload
    # def cloudinary_upload
    #   uploaded_file = params[:content_id][:image].path
    #   cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
    #   render json: cloudinary_file
    # end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!, :is_admin?, only: [:edit, :update, :destroy]
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:create, :update, :destroy]


  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    puts @contents.inspect
    respond_to do |format|
        format.html { render :index}
        format.json { render json: @contents }
      end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show

  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit

  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
     respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:project_type, :body, :image, :accepted, :description)
    end

    def is_admin?
      p '****************************************'
      p !!current_user.is_admin
      p '****************************************'
      redirect_to(root_path) unless !!current_user.is_admin
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_type %>
    <%= f.text_field :project_type %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :accepted %>
    <%= f.check_box :accepted %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= react_component 'Contents', {content: @content, update: true, button_text: 'Update Content'} %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<div class="container contentIndex">
  <div class="row">
    <div class="col-sm-6">
      <h1 id='contentsTitle'>Contents</h1>
      </div>
    <a href="/contents/new"><button class="btn-1" style="float: right;">Create New Content</button></a>
    </div>
    <div class="row1" >
      <% @contents.each do |content| %>
      <%=link_to content do %>
      <div class="col-lg-4 col-sm-6">
        <div class="thumbnail contents">
          <%= image_tag content.image.url %>
        </div>
        <div class="description" style="color:#33995C">
          <%= content.description %>
        </div>
      </div>
      <% end %>
      <% end %>
</div>
</div>

app/views/contents/new.html.erb
<%= react_component 'Contents', {content: @content, update: false, button_text: 'Create Content'} %>

app/views/contents/show.html.erb
<% if !!current_user %>

<%= current_user.inspect %>

<%= react_component 'ContentShow', {content: @content, product_type: @product_type, description: @description, body: @body, image: @content.image_url, update: false, button_text: 'Update Content', current_user: current_user} %>

<% else  %>

<%= react_component 'ContentShow', {content: @content, product_type: @product_type, description: @description, body: @body, image: @content.image_url, update: false, button_text: 'Update Content'} %>

<% end %>